# Site settings
title: Emma Freeman 
header-img: img/home-bg.png
email: freemoe04@gmail.com
copyright_name: Effreeman
description: > # this means to ignore newlines until "baseurl:"
  Just a girl and her code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Effreeman
learn_profile: Effreeman
email_username: freemoe04@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
